<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Novibet.Application\Novibet.Application.csproj" />
        <ProjectReference Include="..\Novibet.Infrastructure\Novibet.Infrastructure.csproj" />
        <ProjectReference Include="..\Novibet.Api\Novibet.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Moq" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>
</Project>